worker_processes auto;
events { worker_connections 1024; }

http {
    # TODO: zdefiniuj blok upstream wskazujący na serwis aplikacji.
    # Nazwa hosta musi być zgodna z nazwą serwisu z docker-compose.yml.
    #
    # upstream <NAZWA> {
    #     server <serwis>:<port>;
    # }
    upstream backend {
	    server app:8000;
    }
    server {
        listen 80;
        server_name _;

        # TODO: dodaj location przekazujący wszystkie żądania do upstreamu.
        location / {
            proxy_pass http://backend;
	    
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
